import { useEffect, useMemo, useState } from "react";
import { Layout } from "../components/Layout";
import { Card } from "../components/Card";
import { api, unwrap } from "../lib/api";
import "./career-readiness.css";

export function Simulator() {
  const [analysis, setAnalysis] = useState<any>(null), [selected, setSelected] = useState<string[]>([]), [result, setResult] = useState<any>(null), [loading, setLoading] = useState(true), [working, setWorking] = useState(false), [error, setError] = useState("");
  useEffect(() => { api.get("/career/readiness").then(unwrap).then(setAnalysis).catch(() => setError("Unable to load your saved readiness analysis.")).finally(() => setLoading(false)); }, []);
  const candidates = useMemo(() => analysis?.skills.filter((item: any) => item.status !== "Strong") || [], [analysis]);
  const toggle = (skill: string) => setSelected((items) => items.includes(skill) ? items.filter((item) => item !== skill) : [...items, skill]);
  const simulate = async () => { if (!analysis) return; try { setWorking(true); setError(""); setResult(unwrap(await api.post("/career/simulate", { targetRole: analysis.targetRole, improvements: selected }))); } catch (err: any) { setError(err.response?.data?.error?.message || "Unable to run the simulation."); } finally { setWorking(false); } };
  return <Layout><section className="hero compact"><p className="eyebrow">WHAT-IF SIMULATOR</p><h1>Test evidence before you build it.</h1><p>Selections are temporary hypothetical project evidence; your profile is never changed.</p></section>{loading && <p>Loading your current readiness…</p>}{error && <p className="error">{error}</p>}{!loading && !analysis && !error && <article className="card empty"><h2>Analyze readiness first</h2><p>Choose a target role on Career Readiness before running a simulation.</p></article>}{analysis && <><section className="grid"><Card title="CURRENT READINESS" value={`${analysis.readiness.overall}%`} text={analysis.targetRole} /><Card title="MISSING SKILLS" value={`${analysis.gaps.length}`} text="Choose skills to simulate" /></section><section className="card"><p className="eyebrow">SELECT HYPOTHETICAL EVIDENCE</p><h2>Missing or unverified target skills</h2><div className="checks">{candidates.map((item: any) => <label key={item.skill}><input type="checkbox" checked={selected.includes(item.skill)} onChange={() => toggle(item.skill)} /> {item.skill} ({item.status})</label>)}</div><button onClick={simulate} disabled={working || !selected.length}>{working ? "Calculating…" : "Simulate improvements"}</button></section>{result && <><section className="comparison card"><div><p className="eyebrow">CURRENT PROFILE</p><h2>{result.current.readiness.overall}%</h2><p>{result.current.readiness.level}</p></div><div><p className="eyebrow">SIMULATED PROFILE</p><h2>{result.simulated.readiness.overall}%</h2><p>{result.scoreChange >= 0 ? "+" : ""}{result.scoreChange} readiness change</p></div></section><section className="grid two"><article className="card"><p className="eyebrow">NEWLY SATISFIED</p><h2>Evidence added</h2>{result.newlySatisfiedSkills.length ? result.newlySatisfiedSkills.map((skill: string) => <p key={skill}>{skill}</p>) : <p>No additional skills became strong.</p>}</article><article className="card"><p className="eyebrow">REMAINING GAPS</p><h2>Still to build</h2>{result.remainingGaps.length ? result.remainingGaps.map((gap: any) => <p key={gap.skill}><b className={`priority ${gap.priority.toLowerCase()}`}>{gap.priority}</b> {gap.skill}</p>) : <p>No target requirements are missing.</p>}</article></section><section className="card"><p className="eyebrow">WHY THE SCORE CHANGED</p><h2>Temporary simulation evidence</h2>{result.simulationEvidence.map((item: any) => <p key={item.skill}><b>{item.skill}:</b> {item.before} → {item.after} ({item.evidence})</p>)}</section></>}</>}</Layout>;
}
